//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentExam.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discipline
    {
        public int DisciplineID { get; set; }
        public Nullable<int> NumberOfHours { get; set; }
        public string Name { get; set; }
        public string CipherID { get; set; }
    
        public virtual Cafedra Cafedra { get; set; }
    }
}
