//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentExam.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student1
    {
        public int IDStudent { get; set; }
        public string Surname { get; set; }
        public string Subject { get; set; }
        public string School { get; set; }
        public Nullable<decimal> Ball { get; set; }
    }
}
