//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentExam.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int RegID { get; set; }
        public string SpecialityID { get; set; }
        public string Surname { get; set; }
    
        public virtual Speciality Speciality { get; set; }
    }
}
