//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentExam.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ученики
    {
        public int ID { get; set; }
        public string Фамилия { get; set; }
        public string Предмет { get; set; }
        public string Школа { get; set; }
        public Nullable<double> Баллы { get; set; }
    }
}
